<!ELEMENT TiendaMoviles (Tiendas, Proveedores, Marcas, Modelos, Moviles, Empleados, Clientes, Ventas)>

<!-- Tiendas -->
<!ELEMENT Tiendas (Tienda+)>
<!ELEMENT Tienda (Nombre, Direccion?, URL?)>
<!ATTLIST Tienda 
    id ID #REQUIRED
    tipo (fisica | online) #REQUIRED>

<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Direccion (#PCDATA)>
<!ELEMENT URL (#PCDATA)>

<!-- Proveedores -->
<!ELEMENT Proveedores (Proveedor+)>
<!ELEMENT Proveedor (Nombre, Contacto)>
<!ATTLIST Proveedor 
    id ID #REQUIRED>

<!ELEMENT Contacto (#PCDATA)>

<!-- Marcas -->
<!ELEMENT Marcas (Marca+)>
<!ELEMENT Marca (NombreMarca, Fabricante, Localizacion)>
<!ATTLIST Marca 
    id ID #REQUIRED>

<!ELEMENT NombreMarca (#PCDATA)>
<!ELEMENT Fabricante (#PCDATA)>
<!ELEMENT Localizacion (#PCDATA)>

<!-- Modelos -->
<!ELEMENT Modelos (Modelo+)>
<!ELEMENT Modelo (NombreModelo, FechaLanzamiento, PromoLanzamiento)>
<!ATTLIST Modelo 
    id ID #REQUIRED
    marca IDREF #REQUIRED>

<!ELEMENT NombreModelo (#PCDATA)>
<!ELEMENT FechaLanzamiento (#PCDATA)>
<!ELEMENT PromoLanzamiento (#PCDATA)>

<!-- Moviles -->
<!ELEMENT Moviles (Movil+)>
<!ELEMENT Movil (PrecioHistorico)>
<!ATTLIST Movil 
    id ID #REQUIRED
    modelo IDREF #REQUIRED
    proveedor IDREF #REQUIRED
    tienda IDREF #REQUIRED>

<!ELEMENT PrecioHistorico (Precio+)>
<!ELEMENT Precio (#PCDATA)>
<!ATTLIST Precio 
    fecha CDATA #REQUIRED>

<!-- Empleados -->
<!ELEMENT Empleados (Empleado+)>
<!ELEMENT Empleado (Nombre, Tienda)>
<!ATTLIST Empleado 
    id ID #REQUIRED>

<!-- Clientes -->
<!ELEMENT Clientes (Cliente+)>
<!ELEMENT Cliente (Nombre)>
<!ATTLIST Cliente 
    id ID #REQUIRED>

<!-- Ventas -->
<!ELEMENT Ventas (Venta+)>
<!ELEMENT Venta (Movil, Empleado, Cliente, Fecha, PrecioVenta)>
<!ATTLIST Venta 
    id ID #REQUIRED>

<!ELEMENT Fecha (#PCDATA)>
<!ELEMENT PrecioVenta (#PCDATA)>
